### ISSUE TITLE
"Error: undefined is not a function"

### ISSUE THREAD

**Issue by rossha** [neocotic/qr.js#27]
Love QR.js, thank you for building it. I had it working in the browser but it has broken for some reason I'm having troubles isolating why. Here is the error I am being thrown:

"TypeError: undefined is not a function
    at Object.X.canvas (http://localhost:8080/app/lib/qr.min.js:4:10052)
    at Object.X.toDataURL (http://localhost:8080/app/lib/qr.min.js:4:10868)
    at http://localhost:8080/app/admin/admin.js:212:26
    (etc.)"

Here is my code:
212    var base64 = qr.toDataURL({
213        mime: 'image/png',
214        value: vip.email,
215        size: 10,
216        level: H
217    }, function(err) {
218    if (err) throw err;
219        console.log(error);
220    });

Any thoughts?

**Comment by neocotic** [comment]
Could you please provide the stack trace using the unminified version.

What version are you using and what browsers (and their versions) are you trying on?

**Comment by rossha** [comment]
TypeError: undefined is not a function
    at Object.qr.canvas (http://localhost:8080/app/lib/qr.js:1036:55)
    at http://localhost:8080/app/admin/admin.js:191:25
    at Scope.$scope.QRcodes (http://localhost:8080/app/admin/admin.js:206:8)
    at http://localhost:8080/app/bower_components/angular/angular.js:10880:21
    at callback (http://localhost:8080/app/bower_components/angular/angular.js:19237:17)
    at Scope.$eval (http://localhost:8080/app/bower_components/angular/angular.js:12788:28)
    at Scope.$apply (http://localhost:8080/app/bower_components/angular/angular.js:12886:23)
    at HTMLAnchorElement.<anonymous> (http://localhost:8080/app/bower_components/angular/angular.js:19242:23)
    at http://localhost:8080/app/bower_components/angular/angular.js:2853:10
    at forEach (http://localhost:8080/app/bower_components/angular/angular.js:325:18)angular.js:10103 (anonymous function)angular.js:7390 (anonymous function)angular.js:12888 Scope.$applyangular.js:19242 (anonymous function)angular.js:2853 (anonymous function)angular.js:325 forEachangular.js:2852 eventHandler

I'm using version 3 on google chrome version 39.0.2171.99

**Comment by neocotic** [comment]
Do you mean version 1.1.3? I'm going to assume yes and continue anyway :) I think this may be a "Doh!" moment but you're value for the `level` option (i.e. "H") is missing quotes so it's not a string. I would have thought that the code would have ignored an undefined value (which I can only guess is what `H` is being evaluated as) but apparently it's not and it's failing when trying to transform it to upper case.

I'll keep investigating but I'm only doing a quick check on my train home right now :)

**Comment by rossha** [comment]
Oh man. You are correct, it is a "Doh!" moment. My sincere apologies for taking up your time, but thank you for your help!

**Comment by neocotic** [comment]
No problem. Glad I could help.

**Comment by neocotic** [comment]
To be honest, `H` couldn't be undefined. So the problem must have also been that you also have another `H` variable defined in that scope that isn't a string. Otherwise you would have got a much more helpful error when attempting to use the undeclared `H` variable. That would also explain why my code tried to transform it to upper case instead of just using the default level.

Anyway, problem solved now.
