### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by niftylettuce** [neocotic/qr.js#36]
I'm not sure how this relates to PM2, but if I run my app without it, it works fine.  Otherwise I get this error:

```
Error: /opt/myproject/node_modules/qr-js/node_modules/canvas/build/Release/canvas.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.cls_wrapMethod [as _load] (/opt/myproject/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/myproject/node_modules/qr-js/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Function.cls_wrapMethod [as _load] (/opt/myproject/node_modules/newrelic/lib/shimmer.js:230:38)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    ...
```

Node `v0.12.7` and NPM `2.11.3`

Possibly related to `pm2` project via <https://github.com/Unitech/PM2/issues/1518>.

**Comment by niftylettuce** [comment]
I think this is due to <https://github.com/Unitech/PM2/issues/1477> so I'm closing this out.

**Comment by neocotic** [comment]
Thanks for taking the time to investigate this and keeping us updated.
