### ISSUE TITLE
Error trying to install - not going to bother troubleshooting

### ISSUE THREAD

**Issue by oh4real** [neocotic/qr.js#41]
Just thought you might like to know:

vagrant@homestead:~/Code/app-gateway$ npm install qr-js --save
npm WARN install Couldn't install optional dependency: Unsupported

> canvas@1.3.5 install /home/vagrant/Code/app-gateway/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: 4: ./util/has_cairo_freetype.sh: pkg-config: not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/Code/app-gateway/node_modules/canvas
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "qr-js" "--save"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/app-gateway/npm-debug.log

Fresh install attempted in vagrant vm with new node/npm. 

I liked your documentation and custom website, but qr-image worked on first pass and I'll see how that goes...

**Comment by oh4real** [comment]
Installed canvas (https://www.npmjs.com/package/canvas) system dependencies. Then it worked.

I'm going to try to use it client-side - and I reckon node-canvas isn't required for client side? 

If not, consider a related version for client-side usage which doesn't have the system dependencies.
